
ansible_python_interpreter: /usr/bin/python3
void_mirror: https://repo-fi.voidlinux.org

timezone: Europe/Paris
keymap: fr
locale: fr_FR

encryption:
  enabled: true
  password: voidlinux

btrfs:
  enabled: true
  subvols: 
    - sub: '@snapshots'
      path: '.snapshots'
    - sub: '@home'
      path: 'home'
    - sub: '@log'
      path: 'var/log'
    - sub: '@cache'
      path: 'var/cache'
    - sub: '@tmp'
      path: 'var/tmp'
    - sub: '@data'
      path: 'data'
      disable_cow: true

install_drive: /dev/vda
swap_size: 2048M

# manual_partitions:
#   - boot: vda1
#   - swap: vda2
#   - root: vda3

hostname: voidlinux
root_password: toor

user:
  name: user
  password: user