# ------ Ansible interpreter
ansible_python_interpreter: /usr/bin/python3

# ------ Machine configuration
void_mirror: https://repo-fi.voidlinux.org
timezone: Europe/Paris
keymap: fr
locale: fr_FR

# ------ Disk Partitionning
encryption:
  enabled: true
  password: voidlinux

btrfs:
  enabled: true
  subvols: 
    - sub: '@snapshots'
      path: '.snapshots'
    - sub: '@home'
      path: 'home'
    - sub: '@log'
      path: 'var/log'
    - sub: '@cache'
      path: 'var/cache'
    - sub: '@tmp'
      path: 'var/tmp'
    - sub: '@data'
      path: 'data'
      disable_cow: true

install_drive: /dev/vda
swap_size: 2048M

# manual_partitions:
#   - boot: vda1
#   - swap: vda2
#   - root: vda3

# ------ Host and user settings
hostname: voidlinux
root_password: toor
user:
  name: user
  password: user

# ------ Software picking list

# Desktop environment
# possible values are: KDE
desktop_environment: KDE

# Web browser
# possible values are: firefox
web_browser: firefox

# Flatpak apps
enable_flatpak: true