- name: Install Pipewire
  community.general.xbps: name=pipewire state=present
  notify:
  - Enable Pipewire on boot

- name: Install bluetooth audio driver
  community.general.xbps: name=libspa-bluetooth state=present