- name: Install kitty terminal
  community.general.xbps: name=kitty state=present

- name: Install Neovim
  community.general.xbps: name=neovim state=present

- name: Install zsh shell
  community.general.xbps: name=zsh state=present

- name: Install Starship prompt
  community.general.xbps: name=starship state=present
  
- name: Change current user's shell to zsh
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh

- name: Set default .zshrc
  template:
    src: zshrc.j2
    dest: "/home/{{ user.name }}/.zshrc"
    owner: "{{ user.name }}"

- name: Install Oh-my-zsh
  become: false
  shell: RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: true

- name: Create font folder
  file:
    state: directory
    path: "/home/{{ user.name }}/.local/share/fonts/"

- name: Copy fonts
  copy:
    src: "fonts/Fira Code Regular Nerd Font Complete Mono.otf" 
    dest: "/home/{{ user.name }}/.local/share/fonts/"
  register: fonts_out

- name: Clear font cache
  shell: fc-cache -f -v
  when: fonts_out.changed
