- name: Install kitty terminal
  community.general.xbps: name=kitty state=present

- name: Install Neovim
  community.general.xbps: name=neovim state=present

- name: Install zsh shell
  community.general.xbps: name=zsh state=present
  
- name: Change current user's shell to zsh
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh

- name: Set default .zshrc
  shell: |
    cat <<EOF > /home/{{ user.name }}/.zshrc
    # Lines configured by zsh-newuser-install
    HISTFILE=~/.histfile
    HISTSIZE=1000
    SAVEHIST=1000
    setopt autocd extendedglob notify
    unsetopt beep nomatch
    bindkey -e
    # End of lines configured by zsh-newuser-install
    # The following lines were added by compinstall
    zstyle :compinstall filename '/home/{{ user.name }}/.zshrc'

    autoload -Uz compinit
    compinit
    # End of lines added by compinstall
    EOF

- name: Install Oh-my-zsh
  become: false
  shell: RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: true