- hosts: voidlinux-live
  gather_facts: false
  become: true
  roles:
  - check_deps

- hosts: voidlinux-live
  become: true
  roles:
  - iso-pre-chroot

- hosts: voidlinux-live
  become: true
  roles:
  - iso-post-chroot