- name: Create user account
  command: chroot /mnt useradd -s /bin/bash -m --user-group -G wheel,users,audio,video,input,network {{ user.name }}

- name: Create user password
  shell: echo "{{ user.name }}:{{ user.password }}" | chpasswd -R /mnt -c SHA512

- name: Create user's ssh directory
  file:
    path: /mnt/home/{{ user.name }}/.ssh
    state: directory
    mode: 0700

# - name: Copy over ssh key from current Ansible controller as an authorized key
#   copy:
#     src: "{{ user.pub_key_location }}"
#     dest: /mnt/home/{{ user.name }}/.ssh/authorized_keys
#     mode: 0600
    
- name: Set mode, owner, and group on user's authorized_key file
  command: chroot /mnt chown -R {{ user.name }}:{{ user.name }} /home/{{ user.name }}/.ssh/

- name: Give passwordless sudo access to wheel group
  copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /mnt/etc/sudoers.d/wheel
    validate: /usr/sbin/visudo --check --file=%s