- name: Set encryption and btrfs fact
  set_fact:
    use_encryption: "{{ encryption is defined and encryption.enabled }}"
    use_btrfs: "{{ btrfs is defined and btrfs.enabled }}"
    root_part: "{{ manual_partitions.root | default(install_drive + '2')}}"
    boot_part: "{{ manual_partitions.boot | default(install_drive + '1')}}"
    hostname: "{{ hostname | default(inventory_hostname | replace('_','-'))}}"

- name: Create Script folder
  file:
    path: /mnt/scripts
    state: directory

# Copy templates
- name: Copy root_passwd template
  template:
    src: root_passwd.j2
    dest: /mnt/scripts/root_passwd.sh
    mode: 755
- name: Copy host_config template
  template:
    src: host_config.j2
    dest: /mnt/scripts/host_config.sh
    mode: 755
- name: Copy genfstab script
  copy:
    src: genfstab.sh
    dest: /mnt/scripts/genfstab.sh
    mode: 755

# Run chrooted scripts
- name: Set root password and give file permission
  command: chroot /mnt /scripts/root_passwd.sh

- name: Set host variables
  command: chroot /mnt /scripts/host_config.sh

- name: Generate fstab
  shell: /mnt/scripts/genfstab.sh -U /mnt | sed -e "s:ArchLinux:VoidLinux:gi" > /mnt/etc/fstab
  register: out
- debug: var=out.stdout_lines
