- name: Set encryption and btrfs fact
  set_fact:
    use_encryption: "{{ encryption is defined and encryption.enabled }}"
    use_btrfs: "{{ btrfs is defined and btrfs.enabled }}"
    root_part: "{{ manual_partitions.root | default(install_drive + '2')}}"
    boot_part: "{{ manual_partitions.boot | default(install_drive + '1')}}"
    hostname: "{{ hostname | default(inventory_hostname | replace('_','-'))}}"

- name: Create Script folder
  file:
    path: /mnt/scripts
    state: directory

- import_tasks: 1-copy-templates.yml
  tags: copy_tmpl

- import_tasks: 2-mount-pts.yml
  tags: mount_pts

# Run chrooted scripts
- name: Set root file permission
  command: chroot /mnt /scripts/root_passwd.sh
- name: Set root password
  shell: echo "root:{{ root_password }}" | chpasswd -R /mnt -c SHA512

- name: Set host variables
  command: chroot /mnt /scripts/host_config.sh

- name: Generate fstab
  shell: /mnt/scripts/genfstab.sh -U /mnt | sed -e "s:ArchLinux:VoidLinux:gi" > /mnt/etc/fstab

- name: Install grub
  shell: chroot /mnt /scripts/grub.sh
#   register: out
# - debug: var=out.stdout_lines

- name: Enable services
  shell: chroot /mnt /scripts/enable_svc.sh

- name: Delete scripts folder
  file:
    path: /mnt/scripts
    state: absent

- import_tasks: 3-user.yml
  tags: user

- name: Reboot
  reboot:
    connect_timeout: 1
    reboot_timeout: 1
  failed_when: false