- name: Install parted
  community.general.xbps: name=parted state=present

- name: Read device information (always use unit when probing)
  community.general.parted: "device={{ install_drive }} unit=MiB"
  register: dev_info

- name: Remove all partitions from disk
  community.general.parted:
    device: "{{ install_drive }}"
    number: '{{ item.num }}'
    state: absent
  loop: '{{ dev_info.partitions }}'
  when: manual_partitions is not defined

- name: Create boot partition
  parted:
    device: '{{ install_drive }}'
    label: gpt
    number: 1
    part_end: 512MB
    name: boot
    flags: [boot, esp]
    state: present
  when: manual_partitions is not defined

- name: Create root partition
  parted:
    device: '{{ install_drive }}'
    label: gpt
    number: 2
    part_start: 512MB
    name: root
    state: present
  when: manual_partitions is not defined

- name: Create FAT32 filesystem in boot partition
  filesystem:
    dev: '{{ boot_part }}'
    fstype: vfat
    opts: -F32
    force: yes
  when: manual_partitions is not defined