# https://wiki.archlinux.org/title/btrfs

- name: Create root
  command: btrfs subvolume create /mnt/@

- name: Create other subvolumes
  command: btrfs subvolume create /mnt/{{ item.sub }}
  loop: "{{ btrfs.subvols }}"

- name: Unmount /mnt
  mount:
    path: /mnt
    state: unmounted

- name: Mount btrfs root subvolume
  mount:
    path: /mnt
    src: '{{ "/dev/mapper/voidcryptroot" if use_encryption else root_part }}'
    fstype: btrfs
    opts: "compress=zstd,discard=async,subvol=@"
    state: mounted

- name: Create mountpoint for btrfs subvolumes
  file:
    path: /mnt/{{ item.path }}
    state: directory
  loop: "{{ btrfs.subvols }}"

- name: Mount btrfs subvolumes
  mount:
    path: /mnt/{{ item.path }}
    src: '{{ "/dev/mapper/voidcryptroot" if use_encryption else root_part }}'
    fstype: btrfs
    opts: "compress=zstd,discard=async,subvol={{ item.sub }}"
    state: mounted
  loop: "{{ btrfs.subvols }}"

- name: Disable CoW for subvols with disable_cow = true
  file:
    path: /mnt/{{ item.path }}
    attributes: C
  loop: "{{ btrfs.subvols }}"
  when: item.disable_cow|default(false)