- name: Update package cache
  community.general.xbps: update_cache=yes

- name: Install base system
  shell: "echo YES | xbps-install -Sy -R {{ void_mirror }}/current -r /mnt base-system btrfs-progs cryptsetup grub-x86_64-efi lvm2 zstd"

- name: Copying remaining files
  block:
  - copy:
      src: /etc/resolv.conf
      dest: /mnt/etc